# yaml-language-server: $schema=./config.schema.json
logging:
  level: info
  request: forbidden
  database: warn
network:
  trustProxy: false
database:
  url: postgresql://depixy:depixy@db:5432/depixy
session:
  secret: this_is_a_secret_key_and_you_must_change_it
  salt: you_must_change_
  # Access token expiry (second)
  expiry: 2592000
feature: {}
